### PR TITLE
Output URL to GCP Logs

### PR DESCRIPTION
**Pull request by ghost**
Prints a link to GCP logs preconfigured with project, region and cluster. 
Link will be broken if release name contains URL unfriendly chars but it wont break the build.

### CODE REVIEW

**Review by arvidgloot — APPROVED** [review]
cool!

**Review by jesigloot — APPROVED** [review]
Very cool :)

May be worth testing out in the local `test.yml` pipeline.
Commenting using some other ready made action such as
https://github.com/unsplash/comment-on-pr

**Comment by ghost** [comment]
> Very cool :)
> 
> May be worth testing out in the local `test.yml` pipeline.
> Commenting using some other ready made action such as
> https://github.com/unsplash/comment-on-pr

Ah, would be super cool to have the link as a comment. But then it needs to be run in a separate step meaning that it's hard to know if it should run before or after the helm upgrade. 

Also, the logs are only interesting when fresh. Waiting too long might make them irrelevant and posting the link as a comment would make it old fast. But to make it more complicated we could add timestamps so that the link points to the specific time window where the helm install was run. Something like from: START_TIME, to: (START_TIME + Helm Timeout)

**Comment by ghost** [comment]
Added the pr comment ideas to https://gloot.atlassian.net/browse/IO-153. Let's first find out if the log url is useful.

**Pull request merged**
